### ISSUE TITLE
Uninstallation instructions

### ISSUE THREAD

**Issue by camachojua** [justinhunt/moodle-mod_readaloud#15]
There is a way to uninstall (via command line) this plugin without visiting  the `admin/plugins.php` page?

**Comment by justinhunt** [comment]
To answer your specific question, you could:

i) delete it from the file system.
I am not sure of the consequences and it will leave junk in the database.
But you can use a tool like Moosh to clean up afterwards:
https://moosh-online.com/commands/

ii) you could look at this:
https://tracker.moodle.org/browse/MDL-35736

But I think the real question is: why do you want to uninstall the plugin without visiting admin ?

If you have a failed install, removing it from the file system is a good thing to do, because it probably did not get in the database yet anyway. And perhaps you put it in the wrong folder or something like that.

**Comment by justinhunt** [comment]
Glad you figured it out. I wonder what was going on ...
